### PR TITLE
Update function

### PR DESCRIPTION
**Pull request by SaaraLeppis**
After some difficulties with wrong push to origin, hope this is ok. 
Please check and merge if all ok.

### CODE REVIEW

**Comment by Termanty** [comment]
Saara, your indentation is 8 spaces. You should use 2 spaces like others are doing.

**Comment by SaaraLeppis** [comment]
> Saara, your indentation is 8 spaces. You should use 2 spaces like others are doing.

Thanks for pointing out, haven't noticed that.

**Comment by MariaRosenholm** [comment]
Do you correct the indentation or shall we merge this as it is? :)

**Comment by SaaraLeppis** [comment]
> Do you correct the indentation or shall we merge this as it is? :)

I think Tero has cleared it for me :D

**Pull request merged**
